name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run main
      run: |
        git clone https://github.com/Jayliu9218/Mail-Reminder-New.git
        cd Mail-Reminder-New
        python main.py
    
    - name: Commit files
      run: |
        git config --local user.email "l921832312@qq.com"
        git config --local user.name "Jayliu9218"
        git ls
        git add info.txt
        git commit -m "AUTO"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
            
    