name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0-23 * * *'
  push:

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - run: pip install -r requirements.txt

    - name: tree
      run: |
        tree

    - name: Run main
      run: |
        git pull
        cat config.txt
        python main.py
        cat config.txt
    
    - name: Commit files
      run: |
        git init
        git config --local user.email "l921832312@qq.com"
        git config --local user.name "Jayliu9218"
        ls
        git add info.txt config.txt
        git commit -m "AUTO"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
            
    